### ISSUE TITLE
Affordance labels????????? WHAT???????????

### ISSUE THREAD

**Issue by pv33** [ivalab/AffKpNet#1]
The viewer won't be able to make to make any sense of the images with affordance labels like 0.0, 1.0, etc.

Especially for the out-of-distribution content. I have no idea what is going on, nor what is being shown. Truly, the page could be tossed out and nothing would change.

Please make an effort to add in information that a first time reader might not be fully aware of. For sure the numeric labeling of the affordance is meaningless to most people. The more someon has to think, the less likely they are to actually understand what you wish to convey.  All results should be clear and obvious. Otherwise, you are not effectively communicating anything to the reader.

Leave this open until I am/we are happy with the messaging of the different supplementary content files.

**Comment by ruinianxu** [comment]
@pv33 
Done. Added textual affordance labels for each figure. Please let me know if it requires further revision,
