### ISSUE TITLE
Camera Matrices

### ISSUE THREAD

**Issue by kevin-so** [ivalab/AffKpNet#4]
Hello!

Thanks for sharing your dataset! I wanted to ask whether you had any information on the camera intrinsics/extrinsics for images? In your paper you mentioned that you used a Intel Realsense and Kinect, could you share specifically which models of those cameras you used?

Thanks!

**Comment by ruinianxu** [comment]
Hi,

For Realsense, it is D435I. For Kinect, it is XBOX360.

Best,
Ruinian Xu

**Comment by kevin-so** [comment]
Thanks for the information! I ended up finding the D435 matrices under `automatic_kp_gen.py`, but forgot to close the issue.
